yamlApplicationConfig:
  kafka:
    clusters:
      - name: mykafka
        bootstrapServers:  mykafka.default.svc.cluster.local:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false