version: '3'
services:
  zookeeper:
    deploy:
      replicas: 1
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    volumes:
      - ../zookeeper-vol/zk-data:/var/lib/zookeeper/data
      - ../zookeeper-vol/zk-txn-logs:/var/lib/zookeeper/log
  
  kafka:
    deploy:
      replicas: 1
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ../kafka-vol/kafka-data:/var/lib/kafka/data

  yfinance-producer:
    build: .
    volumes:
      - ../tickers.txt:/app/tickers.txt
    environment:
      - TZ=UTC
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092