apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
#---
##Use nodePort instead of LoadBalancer if you are using minikube/k3s
#apiVersion: v1
#kind: Service
#metadata:
#  name: kafka-service
#spec:
#  type: NodePort
#  selector:
#    app.kubernetes.io/name: kafka
#  ports:
#    - protocol: TCP
#      port: 9092
#      targetPort: 9092